### ISSUE TITLE
Trying to repro, no package versions given so run_atari fails.

### ISSUE THREAD

**Issue by daniel-vainsencher** [szrlee/HyperAgent#1]
Please specify versions in setup.py, or save a frozen reqs file using pip freeze, etc.

For me, with 

```
$ pip freeze | egrep "atari|gym|ale"
ale-py==0.8.1
atari-py==0.2.9
gym==0.26.2
gym-notices==0.0.8
```

The atari env returns 5 values from step, but the wrappers in atari_wrapper.py expect/return 4.

**Comment by jiawei415** [comment]
@daniel-vainsencher  Thank you for your suggestions. We have uploaded the `requirements.txt` file containing the repository versions we used, and we have also updated the `setup.py` to utilize this `requirements.txt`. Please check the [**Installation**](https://github.com/szrlee/HyperAgent?tab=readme-ov-file#installation) section in the README.md for instructions on how to install the repository.

**Comment by daniel-vainsencher** [comment]
Thanks, will do.
